const itemSubType = {
  0: "None",
  6: "Auto Rifle",
  7: "Shotgun",
  8: "Machine Gun",
  9: "Hand Cannon",
  10: "Rocket Launcher",
  11: "Fusion Rifle",
  12: "Sniper Rifle",
  13: "Pulse Rifle",
  14: "Scout Rifle",
  17: "Sidearm",
  18: "Sword",
  19: "Mask",
  20: "Shader",
  21: "Ornament",
  22: "Linear Fusion Rifle",
  23: "Grenade Launcher",
  24: "Submachine Gun",
  25: "Trace Rifle",
  26: "Helmet Armor",
  27: "Gauntlets Armor",
  28: "Chest Armor",
  29: "Leg Armor",
  30: "Class Armor",
  31: "Bow",
  33: "Glaive",
}

module.exports = itemSubType;